apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: calendar
  namespace: toolhive-system
spec:
  groupRef:
    name: toolhive
  telemetryConfigRef:
    name: toolhive
  externalAuthConfigRef:
    name: entra-upstream
  image: ghcr.io/obot-platform/microsoft-office-365-mcp/microsoft365-calendar:latest@sha256:ce55b522d86ad2149d5147672579d79dc2741240226aff9a9366534c87928fdb
  transport: streamable-http
  mcpPort: 9000
