apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPRemoteProxy
metadata:
  name: github
  namespace: toolhive-system
spec:
  groupRef:
    name: toolhive
  telemetryConfigRef:
    name: toolhive
  remoteUrl: https://api.githubcopilot.com/mcp/x/notifications
  transport: streamable-http
  headerForward:
    addHeadersFromSecret:
      - headerName: Authorization
        valueSecretRef:
          name: toolhive
          key: github-authorization
