apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: github
  namespace: toolhive-system
spec:
  groupRef:
    name: toolhive
  telemetryConfigRef:
    name: toolhive
  image: ghcr.io/github/github-mcp-server:v1.6.0@sha256:2b0c48b070f61e9d3969269ead600f62d00fb237b60ac849ef3d166ee7de9ad3
  transport: streamable-http
  mcpPort: 8082
  args:
    - http
    - --port
    - "8082"
  env:
    - name: GITHUB_TOOLSETS
      value: notifications
  secrets:
    - name: toolhive
      key: github-pat
      targetEnvName: GITHUB_PERSONAL_ACCESS_TOKEN
