apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana
  namespace: toolhive-system
spec:
  groupRef:
    name: toolhive
  telemetryConfigRef:
    name: toolhive
  image: docker.io/grafana/mcp-grafana:0.15.2
  args:
    - -t
    - stdio
  env:
    - name: GRAFANA_URL
      value: https://tplant.grafana.net
  secrets:
    - name: toolhive
      key: grafana-service-account-token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
