apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana
  namespace: toolhive-system
spec:
  groupRef:
    name: toolhive
  telemetryConfigRef:
    name: toolhive
  image: docker.io/grafana/mcp-grafana:1.6.3@sha256:0479c026fd40a95e6a176855b8570e06845790f8a45de2f9c1ec8ba3ba06a8bf
  args:
    - -t
    - stdio
  env:
    - name: GRAFANA_URL
      value: https://tplant.grafana.net
  secrets:
    - name: toolhive
      key: grafana-service-account-token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
