apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana
  namespace: toolhive-system
spec:
  groupRef:
    name: toolhive
  telemetryConfigRef:
    name: toolhive
  image: docker.io/grafana/mcp-grafana:2.0.0@sha256:2ed63c4d9d67557c8ea6cc6988743ddd9008e248bd9842e760fec378a0b61062
  args:
    - -t
    - stdio
  env:
    - name: GRAFANA_URL
      value: https://tplant.grafana.net
  secrets:
    - name: toolhive
      key: grafana-service-account-token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
