kind: Secret
apiVersion: v1
metadata:
    name: cloudflare
    namespace: cloudflare-gateway
type: Opaque
stringData:
    ACCOUNT_ID: ENC[AES256_GCM,data:ouT5fNZYRnlzHRwvFyG2Dq/e3nyX110LbUyoHa7zA+o=,iv:HDu9C65bNwfZkLo5CB35egpxlZCAn/C29/Vz3qD6v60=,tag:++uGMWRPMUQXxIVMByl2Sg==,type:str]
    TOKEN: ENC[AES256_GCM,data:xMpo1WqBYgegBcxCrYqeXhXnWw+SWpuzr0IkQYaw7EPJTejb6UXCWWX25NFoJAZ+F8G3r3Q=,iv:B18HR11qUt7mbK8dDroYLenm9m1KfhjUyvqA2ibeksY=,tag:AlGGX14QGpoDnVpYgFmLHg==,type:str]
sops:
    age:
        - recipient: age18k9804sxqzuxn3pka0x6rgdqp0g7gm7w99g4lu43meqkl9s8lvrsl6n0vh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU1haaDh0amVxaGZzdmJR
            NXFxcXdUNGpERm9DNDFRbVF1ZFRIRzF5bWp3CmtUVGgxMnFuTTdBZTY1SDRMM05v
            TjZ3MzRmaGhDaWl2ZWxUUmZqL2hRZlEKLS0tIGN1WW1yM0x5VWlwOU0rMW5ESy9R
            S0o4Y0VxMGRndjk5VXFSRkVoMHlTWXMKHBa0emodcwOW0DKNk+cMqvRlxMch/M5D
            OnkvvL4EukfmKC7uywUnkW441Z2kSl3lVthW9j2k0V1AphSQnJsjaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T11:25:36Z"
    mac: ENC[AES256_GCM,data:BxfFTCfhpk+J/BHAa8nDDz9FO4TZ1uXFdTi/I9ZG0y9pqHbFZnP1wlxyN5u/jDLGSp69LO3Z3N287lNWwjsep/n+U5agWRWRcJCWKusTRLAyo1FXBZHP3hCWHG0KvBOpwoDTFLWQn0Ch0WYE/20d/YPvREG27kviTTteU251l5w=,iv:/lUM2FBHi8r01DyPnS5bayNADoQgSVLMS+HQMy6GsRI=,tag:c50PzqCMc3/2aKVg9onc/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
